// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhxrajtfxavkkzqyfrok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oeHJhanRmeGF2a2t6cXlmcm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTY5MTIsImV4cCI6MjA3MTAzMjkxMn0.EBVOUTVSTnB7xX97p_h2BDM8VjLSpb_R7VhpbFQBdwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});