// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getCurrentEnvironment } from '@/lib/environment';

const SUPABASE_URL = "https://nhxrajtfxavkkzqyfrok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oeHJhanRmeGF2a2t6cXlmcm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTY5MTIsImV4cCI6MjA3MTAzMjkxMn0.EBVOUTVSTnB7xX97p_h2BDM8VjLSpb_R7VhpbFQBdwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-environment': getCurrentEnvironment(),
    }
  }
});

// Helper to set environment in user's app_metadata via edge function
export async function setUserEnvironment(userId: string) {
  const environment = getCurrentEnvironment();
  
  const maxRetries = 3;
  for (let i = 0; i < maxRetries; i++) {
    try {
      const { error } = await supabase.functions.invoke('set-user-environment', {
        body: { userId, environment }
      });
      
      if (!error) {
        console.log('User environment set successfully:', environment);
        return;
      }
      
      console.warn(`Attempt ${i + 1} failed:`, error);
    } catch (error) {
      console.warn(`Attempt ${i + 1} exception:`, error);
    }
    
    // Wait before next attempt (500ms, 1s, 2s)
    if (i < maxRetries - 1) {
      await new Promise(resolve => setTimeout(resolve, 500 * Math.pow(2, i)));
    }
  }
  
  console.warn('Failed to set user environment after all retries - continuing anyway');
}